name: "PR-Lint"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: 
      group: yahoo-news-alma
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
