name: TypeScript-Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  type-check:
    name: TypeScript Type Check @hackathlone/current
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm@9.15.9

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier
        run: pnpm run format:check

      - name: Run ESLint
        run: pnpm turbo run lint --filter=@hackathlone/current
