name: Typechecks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  type-check:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier
        run: pnpm run format:check

      - name: Run ESLint
        run: pnpm turbo run lint --filter=@hackathlone/current
